-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:01:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Клиенты`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Клиенты` (
  `id_клиента` INT NULL AUTO_INCREMENT,
  `фамилия` VARCHAR(50) NOT NULL,
  `имя` VARCHAR(50) NOT NULL,
  `отчество` VARCHAR(50) NULL,
  `телефон` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_клиента`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Автомобили`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Автомобили` (
  `id_автомобиля` INT NOT NULL AUTO_INCREMENT,
  `марка` VARCHAR(50) NOT NULL,
  `модель` VARCHAR(50) NOT NULL,
  `год` INT NULL,
  `vin` VARCHAR(17) NULL,
  `id_клиента` INT NULL,
  UNIQUE INDEX `vin_UNIQUE` (`vin` ASC) VISIBLE,
  INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,
  CONSTRAINT `Клиенты`
    FOREIGN KEY (`id_клиента`)
    REFERENCES `mydb`.`Клиенты` (`id_клиента`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Услуги`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Услуги` (
  `id_услуги` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `стоимость` DECIMAL(10,2) NOT NULL,
  `время_часы` DECIMAL(4,1) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Запчасти`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Запчасти` (
  `id_запчасти` INT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `артикул` VARCHAR(50) NULL,
  PRIMARY KEY (`id_запчасти`),
  UNIQUE INDEX `артикул_UNIQUE` (`артикул` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Заказ_наряды`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Заказ_наряды` (
  `id_наряда` INT NULL AUTO_INCREMENT,
  `дата` DATE NOT NULL,
  `итоговая_сумма` DECIMAL(10,2) NULL,
  `статус` VARCHAR(20) NOT NULL,
  `id_клиента` INT NULL,
  PRIMARY KEY (`id_наряда`),
  INDEX `Клиенты_idx` (`id_клиента` ASC) VISIBLE,
  CONSTRAINT `Клиенты`
    FOREIGN KEY (`id_клиента`)
    REFERENCES `mydb`.`Клиенты` (`id_клиента`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Услуги_в_наряде`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Услуги_в_наряде` (
  `id_наряда` INT NULL,
  `id_услуги` INT NOT NULL,
  `количество` INT NOT NULL,
  `цена` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_наряда`, `id_услуги`),
  CONSTRAINT `заказ_наряды`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Заказ_наряды` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `услуги`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Услуги` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Запчасти в наряде`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Запчасти в наряде` (
  `id_наряда` INT NULL,
  `id_запчасти` INT NULL,
  `количество` INT NOT NULL,
  `цена` DECIMAL(10,2) NULL,
  `Заказ_наряды_id_наряда` INT NOT NULL,
  PRIMARY KEY (`id_наряда`, `id_запчасти`),
  INDEX `fk_Запчасти в наряде_Заказ_наряды_idx` (`Заказ_наряды_id_наряда` ASC) VISIBLE,
  CONSTRAINT `заказ_наряды`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Заказ_наряды` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `запчасти`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Запчасти` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Запчасти в наряде_Заказ_наряды1`
    FOREIGN KEY (`Заказ_наряды_id_наряда`)
    REFERENCES `mydb`.`Заказ_наряды` (`id_наряда`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
